-- 50 sample location pages for seo_architecture (Deliverable 3).
-- Run after 20260207000001_seo_domination_schema.sql.
-- Uses placeholders 18,000+ in text; no specific prices. Slugs/locations are real for URL structure.

INSERT INTO seo_architecture (page_type, country, region, location, slug, target_keyword, title, meta_description, h1, p1_snippet, pillar_url, internal_links, faq_json, published)
VALUES
-- USA IPTV (10)
('iptv','USA','Texas','Houston','houston','IPTV Houston','Houston IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Houston. Google TV ready. Start free trial today.', '[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[{"url":"/shop","anchor":"Shop"},{"url":"/jailbroken-fire-sticks","anchor":"Jailbroken Fire Sticks"}]','[{"question":"What is IPTV?","answer":"IPTV delivers live TV over the internet. StreamStickPro offers 18,000+ channels for Fire Stick and Google TV."}]',true),
('iptv','USA','California','Los Angeles','los-angeles','IPTV Los Angeles','Los Angeles IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Los Angeles. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[{"url":"/shop","anchor":"Shop"}]','[]',true),
('iptv','USA','New York','New York City','new-york-city','IPTV New York','New York City IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for New York. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[{"url":"/free-trial","anchor":"Free Trial"}]','[]',true),
('iptv','USA','Illinois','Chicago','chicago','IPTV Chicago','Chicago IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Chicago. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','USA','Arizona','Phoenix','phoenix','IPTV Phoenix','Phoenix IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Phoenix. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','USA','Florida','Miami','miami','IPTV Miami','Miami IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Miami. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','USA','Washington','Seattle','seattle','IPTV Seattle','Seattle IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Seattle. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','USA','Colorado','Denver','denver','IPTV Denver','Denver IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Denver. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','USA','Georgia','Atlanta','atlanta','IPTV Atlanta','Atlanta IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Atlanta. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','USA','Massachusetts','Boston','boston','IPTV Boston','Boston IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Boston. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
-- USA Jailbreak (10)
('jailbreak','USA','Texas','Houston','houston','jailbroken Fire Stick Houston','Houston Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Houston. Kodi/Stremio pre-installed. StreamStickPro. Free trial IPTV.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[{"url":"/shop","anchor":"Shop"}]','[]',true),
('jailbreak','USA','California','Los Angeles','los-angeles','jailbroken Fire Stick Los Angeles','Los Angeles Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Los Angeles. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','New York','New York City','new-york-city','jailbroken Fire Stick New York','New York Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for New York. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Florida','Miami','miami','jailbroken Fire Stick Miami','Miami Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Miami. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Illinois','Chicago','chicago','jailbroken Fire Stick Chicago','Chicago Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Chicago. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Arizona','Phoenix','phoenix','jailbroken Fire Stick Phoenix','Phoenix Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Phoenix. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Washington','Seattle','seattle','jailbroken Fire Stick Seattle','Seattle Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Seattle. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Colorado','Denver','denver','jailbroken Fire Stick Denver','Denver Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Denver. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Georgia','Atlanta','atlanta','jailbroken Fire Stick Atlanta','Atlanta Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Atlanta. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
('jailbreak','USA','Massachusetts','Boston','boston','jailbroken Fire Stick Boston','Boston Jailbroken Fire Stick 2026 | StreamStickPro','Pre-jailbroken Fire Stick for Boston. Kodi/Stremio pre-installed. StreamStickPro.','[LOCATION] Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/jailbroken-fire-sticks','[]','[]',true),
-- Canada IPTV (10)
('iptv','CA','Ontario','Toronto','toronto','IPTV Toronto','Toronto IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Toronto. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Quebec','Montreal','montreal','IPTV Montreal','Montreal IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Montreal. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','British Columbia','Vancouver','vancouver','IPTV Vancouver','Vancouver IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Vancouver. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Alberta','Calgary','calgary','IPTV Calgary','Calgary IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Calgary. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Alberta','Edmonton','edmonton','IPTV Edmonton','Edmonton IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Edmonton. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Ontario','Ottawa','ottawa','IPTV Ottawa','Ottawa IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Ottawa. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Quebec','Quebec City','quebec-city','IPTV Quebec City','Quebec City IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Quebec City. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Manitoba','Winnipeg','winnipeg','IPTV Winnipeg','Winnipeg IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Winnipeg. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Nova Scotia','Halifax','halifax','IPTV Halifax','Halifax IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Halifax. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','CA','Saskatchewan','Saskatoon','saskatoon','IPTV Saskatoon','Saskatoon IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Saskatoon. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
-- UK IPTV (10)
('iptv','UK','England','London','london','IPTV London','London IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for London. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','England','Manchester','manchester','IPTV Manchester','Manchester IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Manchester. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','Scotland','Glasgow','glasgow','IPTV Glasgow','Glasgow IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Glasgow. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','England','Birmingham','birmingham','IPTV Birmingham','Birmingham IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Birmingham. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','England','Leeds','leeds','IPTV Leeds','Leeds IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Leeds. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','Wales','Cardiff','cardiff','IPTV Cardiff','Cardiff IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Cardiff. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','Northern Ireland','Belfast','belfast','IPTV Belfast','Belfast IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Belfast. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','England','Liverpool','liverpool','IPTV Liverpool','Liverpool IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Liverpool. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','England','Bristol','bristol','IPTV Bristol','Bristol IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Bristol. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
('iptv','UK','England','Sheffield','sheffield','IPTV Sheffield','Sheffield IPTV + Jailbroken Fire Stick Guide 2026 | StreamStickPro','StreamStickPro: 18,000+ IPTV channels + jailbroken Fire Sticks for Sheffield. Google TV ready. Free trial.','[LOCATION] IPTV + Jailbroken Fire Stick Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-services','[]','[]',true),
-- Google TV (10)
('google','USA','Texas','Houston','houston','Google TV IPTV Houston','Houston Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Houston. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','USA','California','Los Angeles','los-angeles','Google TV IPTV Los Angeles','Los Angeles Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Los Angeles. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','CA','Ontario','Toronto','toronto','Google TV IPTV Toronto','Toronto Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Toronto. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','UK','England','London','london','Google TV IPTV London','London Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for London. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','USA','New York','New York City','new-york-city','Google TV IPTV New York','New York Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for New York. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','CA','Quebec','Montreal','montreal','Google TV IPTV Montreal','Montreal Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Montreal. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','CA','British Columbia','Vancouver','vancouver','Google TV IPTV Vancouver','Vancouver Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Vancouver. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','UK','England','Manchester','manchester','Google TV IPTV Manchester','Manchester Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Manchester. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','USA','Illinois','Chicago','chicago','Google TV IPTV Chicago','Chicago Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Chicago. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true),
('google','USA','Florida','Miami','miami','Google TV IPTV Miami','Miami Google TV IPTV 2026 | StreamStickPro','IPTV on Google TV for Miami. StreamStickPro 18,000+ channels. Chromecast compatible. Free trial.','[LOCATION] Google TV IPTV Guide 2026','StreamStickPro delivers 18,000+ IPTV channels + jailbroken Fire Sticks with Kodi/Stremio pre-installed. Works Google TV/Chromecast. Free trial available.','/iptv-media-players','[]','[]',true)
ON CONFLICT (page_type, country, slug) DO NOTHING;
