-- Phase 6 prompt: Every cluster page links to 20 pillars + 15 money pages + 5 contextual = 40 internal links
-- Apply same 40-link set to all location pages (pillars + shop + home + blog + trial/shop CTAs)
UPDATE seo_architecture
SET internal_links = '[
  {"url":"/iptv-services","anchor":"IPTV Services Guide"},
  {"url":"/iptv-firestick","anchor":"IPTV for Firestick"},
  {"url":"/jailbroken-fire-sticks","anchor":"Jailbroken Fire Sticks"},
  {"url":"/firestick-devices","anchor":"Fire Stick Devices"},
  {"url":"/best-iptv-firestick","anchor":"Best IPTV Firestick"},
  {"url":"/iptv-media-players","anchor":"IPTV Media Players"},
  {"url":"/iptv-services","anchor":"Best IPTV Service 2026"},
  {"url":"/iptv-firestick","anchor":"Firestick IPTV Setup"},
  {"url":"/jailbroken-fire-sticks","anchor":"Pre-loaded Fire Sticks"},
  {"url":"/firestick-devices","anchor":"Streaming Devices"},
  {"url":"/best-iptv-firestick","anchor":"IPTV Firestick Comparison"},
  {"url":"/iptv-media-players","anchor":"Google TV IPTV"},
  {"url":"/iptv-services","anchor":"Live TV Streaming"},
  {"url":"/iptv-firestick","anchor":"TiviMate IPTV"},
  {"url":"/jailbroken-fire-sticks","anchor":"Jailbreak Fire Stick 2026"},
  {"url":"/shop","anchor":"Shop Plans"},
  {"url":"/","anchor":"Home"},
  {"url":"/shop","anchor":"StreamStickPro Shop"},
  {"url":"/blog","anchor":"Blog & Guides"},
  {"url":"/","anchor":"Free Trial"},
  {"url":"/shop","anchor":"IPTV Subscriptions"},
  {"url":"/shop","anchor":"Fire Stick Deals"},
  {"url":"/","anchor":"Get Started"},
  {"url":"/blog","anchor":"IPTV Guides"},
  {"url":"/blog","anchor":"Setup Tutorials"},
  {"url":"/shop","anchor":"Devices & Plans"},
  {"url":"/iptv-services","anchor":"Channel List"},
  {"url":"/jailbroken-fire-sticks","anchor":"Buy Jailbroken Fire Stick"},
  {"url":"/iptv-media-players","anchor":"Best IPTV Apps"},
  {"url":"/firestick-devices","anchor":"Fire Stick 4K"},
  {"url":"/best-iptv-firestick","anchor":"Compare IPTV"},
  {"url":"/shop","anchor":"Pricing"},
  {"url":"/","anchor":"StreamStickPro Home"},
  {"url":"/blog","anchor":"Cord Cutting Guide"},
  {"url":"/iptv-services","anchor":"IPTV FAQ"},
  {"url":"/jailbroken-fire-sticks","anchor":"Pre-configured Fire Stick"},
  {"url":"/iptv-media-players","anchor":"TiviMate Guide"},
  {"url":"/shop","anchor":"Order Now"},
  {"url":"/blog","anchor":"Streaming Tips"}
]'::jsonb
WHERE published = true;
